package com.pek.codegenerator.jdbc;

public class DatabaseSql {
    public final static String ORACLE_SQL = "SELECT T.COLUMN_NAME, T.DATA_TYPE ,T.DATA_LENGTH,T.DATA_PRECISION,T.DATA_SCALE,C.COMMENTS FROM USER_TAB_COLUMNS T ,USER_COL_COMMENTS C WHERE T.COLUMN_NAME=C.COLUMN_NAME AND C.TABLE_NAME=T.TABLE_NAME AND T.TABLE_NAME=?";
    public final static String MYSQL_SQL = "SELECT COLUMN_NAME,DATA_TYPE,COLUMN_COMMENT COMMENTS FROM COLUMNS T WHERE T.TABLE_NAME=?";
}
